apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: astrbot
  name: astrbot
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: astrbot
  strategy:
      type: Recreate    
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chrome-default: "true"
        io.kompose.service: astrbot
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: Asia/Shanghai
        image: soulter/astrbot:v3.5.24
        name: test
        ports:
        - containerPort: 6185
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - mountPath: /AstrBot/data
          name: app-data-data
        - mountPath: /etc/localtime:ro
          name: app-data-etc-localtime
      restartPolicy: Always
      volumes:
      - hostPath:
          path: '{{ .Values.userspace.appData }}/data'
          type: DirectoryOrCreate
        name: app-data-data
      - hostPath:
          path: '{{ .Values.userspace.appData }}/etc/localtime'
          type: DirectoryOrCreate
        name: app-data-etc-localtime
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: astrbot
  name: astrbot
  namespace: '{{ .Release.Namespace }}'
spec:
  ports:
  - name: "6185"
    port: 6185
    targetPort: 6185
  selector:
    io.kompose.service: astrbot
status:
  loadBalancer: {}
